# 'data_root': "/home/sqz/Desktop/yebw/gazebo/data"
'data_root': "/root/project/final_project-2/data/and_or"

'batch_size': 10

'max_epochs': 18
'last_epoch': 6

'continue_epoch': 10

'lr': 0.00001
"val_epoch": 1
"save_epoch": 1


'embed_dim': 512
'seq_len': 80  # 给了0,预测1-80


'save_dir': 'output/models'
'ten_dir': 'output/tensorboard'


'test_result': '/root/project/final_project-2/baseline-0/test_result_andor'
